#!/usr/bin/env ruby
# frozen_string_literal: true

# Set default external encoding to UTF-8
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

require 'jackdaw'

Jackdaw::CLI.start(ARGV)
